# Naive Bayes

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv("play_tennis.csv")

In [3]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
data.drop(columns=['day'],inplace=True)

In [5]:
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [6]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [7]:
py=9/14
pn=5/14

In [8]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [9]:
#  outlooks 
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [11]:
# temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
pcoolno=1/5
photno=2/5
pmildno=2/5

pcooltes=3/9
phottes=2/9
pmildyes=4/9

In [13]:
# humaidity
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [16]:
phighno=4/5
phormalno=1/5

phighyes=3/9
phormalyes=6/9

In [17]:
# wind 
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [18]:
pstrongno=3/5
pweakno=2/5

pstrongyes=3/9
pweakyes=6/9